
// Auto-generated by btech CLI — type declarations for @btech/assets
declare module '@btech/assets/anim/*.json' {
  const value: Record<string, unknown>;
  export default value;
}
declare module '@btech/assets/illus/*.png' {
  const src: string;
  export default src;
}
