/**
 * Emoji dataset for BTInputRichEditor picker.
 * Each entry: [emoji, space-separated keywords (lowercase)]
 * Keywords drive the search filter.
 */

export interface EmojiCategory {
  id:     string;
  name:   string;
  icon:   string;            // representative emoji shown in the tab
  emojis: [string, string][]; // [char, keywords]
}

export const EMOJI_CATEGORIES: EmojiCategory[] = [
  {
    id: 'smileys', name: 'Smileys & Emotion', icon: '😀',
    emojis: [
      ['😀','happy smile grinning'],
      ['😃','smile happy big eyes'],
      ['😄','grin happy laugh smile'],
      ['😁','beaming grin happy'],
      ['😆','laughing happy haha'],
      ['😅','sweat smile nervous'],
      ['😂','joy laugh cry funny'],
      ['🤣','rolling laugh floor'],
      ['🥲','smiling tear grateful'],
      ['😊','smiling blush happy'],
      ['😇','angel innocent halo'],
      ['🙂','slightly smile'],
      ['🙃','upside smile sarcasm'],
      ['😉','wink playful'],
      ['😌','relieved peaceful'],
      ['😍','heart eyes love adore'],
      ['🥰','love smiling hearts'],
      ['😘','kiss blow love'],
      ['😗','kiss whistle'],
      ['😙','kiss smile'],
      ['😚','kiss closed eyes'],
      ['😋','yum tongue delicious'],
      ['😛','tongue playful'],
      ['😝','tongue squinting'],
      ['😜','winking tongue'],
      ['🤪','zany crazy silly'],
      ['🤨','raised eyebrow skeptical'],
      ['🧐','monocle curious smart'],
      ['🤓','nerd glasses smart'],
      ['😎','sunglasses cool'],
      ['🥸','disguise incognito'],
      ['🤩','star eyes wow excited'],
      ['🥳','party celebrate hat'],
      ['😏','smirk confident'],
      ['😒','unamused annoyed'],
      ['😞','disappointed sad'],
      ['😔','pensive sad thoughtful'],
      ['😟','worried anxious'],
      ['😕','confused unsure'],
      ['🙁','slightly frowning sad'],
      ['☹️','frowning sad unhappy'],
      ['😣','persevere struggle'],
      ['😖','confounded confused'],
      ['😫','tired exhausted'],
      ['😩','weary tired'],
      ['🥺','pleading puppy eyes'],
      ['😢','cry sad tear'],
      ['😭','loudly cry sob'],
      ['😤','angry snort steam'],
      ['😠','angry mad'],
      ['😡','pouting rage angry'],
      ['🤬','swearing cursing angry'],
      ['🤯','exploding head shocked'],
      ['😳','flushed embarrassed'],
      ['🥵','hot sweating flushed'],
      ['🥶','cold freezing'],
      ['😱','scream fear shocked'],
      ['😨','fearful scared'],
      ['😰','anxious sweat nervous'],
      ['😥','sad relieved'],
      ['😓','downcast sweat'],
      ['🤗','hugging warm embrace'],
      ['🤔','thinking hmm pondering'],
      ['🫡','salute respect'],
      ['🤭','hand over mouth oops'],
      ['🤫','shushing quiet secret'],
      ['🤥','lying pinocchio'],
      ['😶','no mouth speechless'],
      ['😐','neutral expressionless'],
      ['😑','expressionless blank'],
      ['😬','grimace awkward'],
      ['🙄','eye roll sarcasm'],
      ['😯','hushed surprised'],
      ['😦','frowning surprised'],
      ['😧','anguished distressed'],
      ['😮','open mouth surprised'],
      ['😲','astonished shocked'],
      ['🥱','yawning tired bored'],
      ['😴','sleep zzz tired'],
      ['🤤','drooling hungry'],
      ['😪','sleepy tired'],
      ['😵','dizzy spiral confused'],
      ['🤐','zipper mouth secret'],
      ['🥴','woozy drunk'],
      ['🤢','nauseated sick gross'],
      ['🤮','vomit sick'],
      ['🤧','sneezing sick cold'],
      ['😷','mask sick medical'],
      ['🤒','thermometer sick fever'],
      ['🤕','bandage hurt injured'],
      ['🤑','money face rich'],
      ['🤠','cowboy hat western'],
      ['👻','ghost scary halloween'],
      ['💀','skull death danger'],
      ['☠️','skull crossbones poison'],
      ['👽','alien ufo extraterrestrial'],
      ['🤖','robot ai machine'],
      ['💩','poop funny gross'],
      ['😈','devil evil grin'],
      ['👿','angry devil'],
      ['❤️','heart love red'],
      ['🧡','orange heart'],
      ['💛','yellow heart'],
      ['💚','green heart'],
      ['💙','blue heart'],
      ['💜','purple heart'],
      ['🖤','black heart'],
      ['🤍','white heart'],
      ['💔','broken heart sad'],
      ['💕','two hearts love'],
      ['💞','revolving hearts love'],
      ['💓','beating heart love'],
      ['💗','growing heart love'],
      ['💖','sparkling heart love'],
      ['💘','arrow heart cupid'],
      ['💝','ribbon heart gift love'],
    ],
  },
  {
    id: 'people', name: 'People & Body', icon: '👋',
    emojis: [
      ['👋','wave hello goodbye'],
      ['🤚','raised back hand stop'],
      ['🖐️','hand five fingers'],
      ['✋','raised hand stop'],
      ['🖖','vulcan salute spock'],
      ['🫱','hand right'],
      ['🫲','hand left'],
      ['👌','ok perfect'],
      ['🤌','pinched fingers italian'],
      ['🤏','small tiny pinch'],
      ['✌️','peace victory two'],
      ['🤞','crossed fingers luck'],
      ['🤟','love you gesture'],
      ['🤘','rock horns metal'],
      ['🤙','call me hang loose'],
      ['👈','point left'],
      ['👉','point right'],
      ['👆','point up'],
      ['🖕','middle finger rude'],
      ['👇','point down'],
      ['☝️','index point up'],
      ['👍','thumbs up like yes'],
      ['👎','thumbs down dislike no'],
      ['✊','raised fist punch'],
      ['👊','oncoming fist punch'],
      ['🤛','left fist bump'],
      ['🤜','right fist bump'],
      ['👏','clap applause'],
      ['🙌','celebration hands raised'],
      ['👐','open hands'],
      ['🤲','palms together prayer'],
      ['🤝','handshake deal'],
      ['🙏','pray thank folded hands'],
      ['✍️','writing pen'],
      ['💅','nails polish manicure'],
      ['🤳','selfie phone camera'],
      ['💪','muscle strong flex'],
      ['🦵','leg kick'],
      ['🦶','foot footprint'],
      ['👂','ear listen'],
      ['👃','nose smell'],
      ['👀','eyes look see'],
      ['👁️','eye vision'],
      ['👅','tongue taste'],
      ['👄','mouth lips kiss'],
      ['🫂','hug embrace'],
      ['👶','baby infant'],
      ['👧','girl child'],
      ['🧒','child kid'],
      ['👦','boy child'],
      ['👩','woman female'],
      ['🧑','person adult'],
      ['👨','man male'],
      ['👩‍⚕️','woman doctor nurse'],
      ['👨‍⚕️','man doctor nurse'],
      ['👩‍🎓','woman graduate student'],
      ['👨‍🎓','man graduate student'],
      ['👩‍💼','woman office worker'],
      ['👨‍💼','man office worker'],
      ['🧑‍💻','technologist coder'],
      ['👩‍🍳','woman cook chef'],
      ['👨‍🍳','man cook chef'],
      ['👮','police officer cop'],
      ['💂','guard royal'],
      ['🕵️','detective spy'],
      ['👰','bride wedding'],
      ['🤵','tuxedo groom'],
      ['🎅','santa claus christmas'],
      ['🤶','mrs claus christmas'],
      ['🧙','mage wizard magic'],
      ['🧝','elf fairy'],
      ['🧛','vampire dracula'],
      ['🧟','zombie undead'],
      ['🧜','mermaid fish tail'],
      ['🧚','fairy wings'],
      ['👼','angel baby wings'],
      ['🤺','fencer sword'],
      ['🏇','horse racing jockey'],
      ['⛷️','skier skiing snow'],
      ['🏂','snowboarder snow'],
      ['🏌️','golfer golf'],
      ['🏄','surfer wave surfing'],
      ['🚣','rowing boat oar'],
      ['🏊','swimming pool swimmer'],
      ['⛹️','basketball player'],
      ['🏋️','weight lifter gym'],
      ['🚴','cyclist biking'],
      ['🚵','mountain biking'],
      ['🤸','gymnastics cartwheel'],
      ['🤼','wrestling grapple'],
      ['🤽','water polo swim'],
      ['🤾','handball throw'],
      ['🤺','fencing sword'],
      ['🏇','jockey racing horse'],
    ],
  },
  {
    id: 'animals', name: 'Animals & Nature', icon: '🐒',
    emojis: [
      ['🐶','dog puppy pet'],
      ['🐱','cat kitten pet'],
      ['🐭','mouse rodent'],
      ['🐹','hamster pet'],
      ['🐰','rabbit bunny'],
      ['🦊','fox red animal'],
      ['🐻','bear animal'],
      ['🐼','panda bamboo bear'],
      ['🐨','koala australia'],
      ['🐯','tiger stripe cat'],
      ['🦁','lion king roar'],
      ['🐮','cow moo farm'],
      ['🐷','pig oink farm'],
      ['🐸','frog green jump'],
      ['🐵','monkey face'],
      ['🙈','see no evil monkey'],
      ['🙉','hear no evil monkey'],
      ['🙊','speak no evil monkey'],
      ['🐒','monkey primate'],
      ['🐔','chicken farm bird'],
      ['🐧','penguin ice arctic'],
      ['🐦','bird tweet'],
      ['🦆','duck quack'],
      ['🦅','eagle bird predator'],
      ['🦉','owl wise night'],
      ['🦇','bat night vampire'],
      ['🐺','wolf howl'],
      ['🐗','boar pig wild'],
      ['🐴','horse face'],
      ['🦄','unicorn magic'],
      ['🐝','bee honey insect'],
      ['🦋','butterfly insect'],
      ['🐌','snail slow'],
      ['🐞','ladybug beetle insect'],
      ['🐜','ant insect'],
      ['🦟','mosquito insect bite'],
      ['🦗','cricket insect'],
      ['🕷️','spider web'],
      ['🦂','scorpion sting'],
      ['🐢','turtle slow shell'],
      ['🐍','snake reptile'],
      ['🦎','lizard reptile'],
      ['🦖','dinosaur t-rex'],
      ['🦕','dinosaur brontosaurus'],
      ['🐙','octopus tentacles sea'],
      ['🦑','squid sea'],
      ['🦐','shrimp seafood'],
      ['🦞','lobster seafood'],
      ['🦀','crab seafood'],
      ['🐡','pufferfish sea'],
      ['🐠','tropical fish sea'],
      ['🐟','fish sea'],
      ['🐬','dolphin sea'],
      ['🐳','whale sea water spout'],
      ['🦈','shark dangerous sea'],
      ['🐊','crocodile alligator'],
      ['🦓','zebra stripe'],
      ['🦍','gorilla ape primate'],
      ['🐘','elephant trunk'],
      ['🦛','hippo thick'],
      ['🦏','rhino horn'],
      ['🐪','camel desert hump'],
      ['🦒','giraffe neck tall'],
      ['🦬','bison buffalo'],
      ['🐃','water buffalo farm'],
      ['🐄','cow milk farm'],
      ['🐎','horse race fast'],
      ['🐏','ram sheep'],
      ['🐑','sheep wool ewe'],
      ['🦙','llama peru'],
      ['🐐','goat mountain'],
      ['🦌','deer antler'],
      ['🐕','dog pet loyal'],
      ['🐈','cat pet feline'],
      ['🌵','cactus desert'],
      ['🌲','tree pine nature'],
      ['🌳','tree nature deciduous'],
      ['🌴','palm tree tropical'],
      ['🌱','seedling plant grow'],
      ['🌿','herb leaf green'],
      ['☘️','shamrock lucky clover'],
      ['🍀','four leaf clover lucky'],
      ['🍃','leaves wind'],
      ['🍂','autumn leaves fall'],
      ['🍁','maple leaf canada fall'],
      ['🍄','mushroom fungi'],
      ['🌾','sheaf rice grain'],
      ['💐','bouquet flowers'],
      ['🌷','tulip flower'],
      ['🌹','rose flower love'],
      ['🥀','wilted flower sad'],
      ['🌺','hibiscus flower tropical'],
      ['🌸','cherry blossom flower'],
      ['🌼','blossom flower yellow'],
      ['🌻','sunflower yellow'],
      ['🌞','sun happy warm'],
      ['🌈','rainbow colorful'],
      ['⭐','star night sky'],
      ['🌙','crescent moon night'],
      ['❄️','snowflake cold winter'],
      ['🌊','wave ocean water'],
      ['💧','drop water liquid'],
      ['🔥','fire hot flame'],
    ],
  },
  {
    id: 'food', name: 'Food & Drink', icon: '🍇',
    emojis: [
      ['🍇','grape fruit purple'],
      ['🍈','melon fruit green'],
      ['🍉','watermelon fruit summer'],
      ['🍊','tangerine orange fruit'],
      ['🍋','lemon sour fruit'],
      ['🍌','banana yellow fruit'],
      ['🍍','pineapple tropical fruit'],
      ['🥭','mango tropical fruit'],
      ['🍎','apple red fruit'],
      ['🍏','apple green fruit'],
      ['🍐','pear fruit green'],
      ['🍑','peach fruit'],
      ['🍒','cherries fruit red'],
      ['🍓','strawberry fruit red'],
      ['🫐','blueberry fruit'],
      ['🥝','kiwi fruit green'],
      ['🍅','tomato red vegetable'],
      ['🫒','olive mediterranean'],
      ['🥥','coconut tropical'],
      ['🥑','avocado green'],
      ['🍆','eggplant purple vegetable'],
      ['🥔','potato vegetable'],
      ['🥕','carrot vegetable orange'],
      ['🌽','corn vegetable yellow'],
      ['🌶️','pepper hot spicy'],
      ['🥦','broccoli vegetable green'],
      ['🧄','garlic spicy'],
      ['🧅','onion vegetable'],
      ['🍄','mushroom fungi'],
      ['🥜','peanut nut'],
      ['🌰','chestnut nut fall'],
      ['🍞','bread toast'],
      ['🥐','croissant french breakfast'],
      ['🥖','baguette french bread'],
      ['🥨','pretzel salty'],
      ['🧀','cheese dairy'],
      ['🥚','egg breakfast'],
      ['🍳','egg frying pan breakfast'],
      ['🧇','waffle breakfast sweet'],
      ['🥞','pancakes breakfast maple'],
      ['🥓','bacon breakfast meat'],
      ['🥩','steak meat beef'],
      ['🍗','chicken drumstick'],
      ['🍖','meat bone bbq'],
      ['🌭','hotdog frank sausage'],
      ['🍔','burger hamburger fast food'],
      ['🍟','fries french food'],
      ['🍕','pizza slice'],
      ['🌮','taco mexican'],
      ['🌯','burrito wrap'],
      ['🥙','stuffed flatbread'],
      ['🥗','salad green healthy'],
      ['🍛','curry rice'],
      ['🍜','noodle ramen soup'],
      ['🍝','spaghetti pasta'],
      ['🍣','sushi fish rice japanese'],
      ['🍱','bento box japanese'],
      ['🍙','rice ball japanese'],
      ['🍚','rice bowl'],
      ['🥟','dumpling dim sum'],
      ['🦪','oyster seafood'],
      ['🧁','cupcake cake sweet'],
      ['🍰','cake slice sweet birthday'],
      ['🎂','birthday cake celebrate'],
      ['🍮','custard dessert'],
      ['🍭','lollipop candy sweet'],
      ['🍬','candy sweet'],
      ['🍫','chocolate sweet'],
      ['🍿','popcorn movie snack'],
      ['🍩','donut sweet'],
      ['🍪','cookie sweet bake'],
      ['🍯','honey sweet jar'],
      ['☕','coffee hot morning'],
      ['🍵','tea hot cup'],
      ['🫖','teapot brew'],
      ['🍶','sake japanese rice wine'],
      ['🍺','beer mug drink'],
      ['🍻','cheers beer mugs'],
      ['🥂','champagne toast celebrate'],
      ['🍷','wine red glass'],
      ['🥃','whiskey tumbler glass'],
      ['🍸','cocktail martini'],
      ['🍹','tropical drink cocktail'],
      ['🧉','mate drink straw'],
      ['🍾','champagne bottle celebrate'],
      ['🧃','juice box drink'],
      ['🥤','cup straw soda drink'],
      ['🧋','bubble tea boba milk tea'],
      ['🧊','ice cube cold'],
    ],
  },
  {
    id: 'travel', name: 'Travel & Places', icon: '🌍',
    emojis: [
      ['🌍','earth globe africa europe'],
      ['🌎','earth globe america'],
      ['🌏','earth globe asia'],
      ['🗺️','world map travel'],
      ['🧭','compass direction navigate'],
      ['🏔️','mountain peak snow'],
      ['⛰️','mountain nature'],
      ['🌋','volcano eruption'],
      ['🏕️','camping tent outdoor'],
      ['🏖️','beach sand sun'],
      ['🏜️','desert sand hot'],
      ['🏝️','island tropical beach'],
      ['🏟️','stadium sports'],
      ['🏛️','classical building column'],
      ['🏗️','construction building'],
      ['🏠','house home'],
      ['🏡','garden house home'],
      ['🏢','office building'],
      ['🏥','hospital medical'],
      ['🏦','bank money'],
      ['🏨','hotel travel'],
      ['🏪','convenience store'],
      ['🏫','school education'],
      ['🏬','department store'],
      ['🏭','factory industry'],
      ['🏯','castle japan'],
      ['🏰','castle medieval'],
      ['🗼','tokyo tower'],
      ['🗽','statue liberty usa'],
      ['⛪','church religion'],
      ['🕌','mosque islam'],
      ['🕍','synagogue jewish'],
      ['⛩️','shinto shrine japan'],
      ['⛲','fountain park'],
      ['⛺','tent camping'],
      ['🌃','night city stars'],
      ['🏙️','city skyline urban'],
      ['🌄','sunrise mountain'],
      ['🌅','sunrise dawn'],
      ['🌆','city dusk sunset'],
      ['🌇','city sunset'],
      ['🌉','bridge night city'],
      ['🎠','carousel fun fair'],
      ['🎡','ferris wheel fun'],
      ['🎢','roller coaster amusement'],
      ['🚂','train steam locomotive'],
      ['🚄','bullet train speed'],
      ['🚇','metro subway'],
      ['🚌','bus transit'],
      ['🚑','ambulance emergency'],
      ['🚒','fire truck emergency'],
      ['🚓','police car cop'],
      ['🚕','taxi cab'],
      ['🚗','car automobile'],
      ['🚙','suv car'],
      ['🚚','truck delivery'],
      ['🚜','tractor farm'],
      ['🏎️','racing car fast'],
      ['🏍️','motorcycle bike'],
      ['🚲','bicycle bike cycling'],
      ['✈️','airplane fly travel'],
      ['🚁','helicopter fly'],
      ['🚀','rocket space launch'],
      ['🛸','ufo flying saucer'],
      ['🛶','canoe boat'],
      ['⛵','sailboat sail'],
      ['🚢','ship cruise'],
      ['⚓','anchor sea boat'],
      ['🗺️','map travel world'],
      ['🧳','luggage travel suitcase'],
      ['🚏','bus stop transit'],
      ['⛽','fuel gas station'],
      ['🚦','traffic light'],
      ['🗺️','map travel world'],
    ],
  },
  {
    id: 'activities', name: 'Activities', icon: '⚽',
    emojis: [
      ['⚽','soccer football sport'],
      ['🏀','basketball sport'],
      ['🏈','american football sport'],
      ['⚾','baseball sport'],
      ['🎾','tennis sport'],
      ['🏐','volleyball sport'],
      ['🏉','rugby sport'],
      ['🎱','billiard pool ball eight'],
      ['🏓','ping pong table tennis'],
      ['🏸','badminton racket'],
      ['🏒','ice hockey sport'],
      ['🏑','field hockey sport'],
      ['🥊','boxing glove fight'],
      ['🥋','martial arts karate'],
      ['⛳','golf course hole'],
      ['🎣','fishing rod hook'],
      ['🤿','scuba diving snorkel'],
      ['🎿','ski snow winter'],
      ['⛷️','skiing snow winter'],
      ['🏂','snowboard snow'],
      ['🪂','parachute sky dive'],
      ['🏋️','weight lifting gym muscle'],
      ['🤼','wrestling fight'],
      ['🤸','gymnastics flip'],
      ['⛹️','basketball player'],
      ['🤾','handball throw'],
      ['🏇','horse racing'],
      ['🧘','yoga meditation mindful'],
      ['🏄','surfing wave'],
      ['🏊','swimming pool'],
      ['🚣','rowing boat'],
      ['🧗','climbing wall rock'],
      ['🚵','mountain bike'],
      ['🚴','cycling bike'],
      ['🏆','trophy win champion'],
      ['🥇','gold medal first place'],
      ['🥈','silver medal second'],
      ['🥉','bronze medal third'],
      ['🏅','medal sport'],
      ['🎖️','military medal honor'],
      ['🎗️','ribbon awareness'],
      ['🎫','ticket event'],
      ['🎪','circus tent performance'],
      ['🤹','juggling performance'],
      ['🎭','theatre drama masks'],
      ['🎨','art palette painting'],
      ['🎬','clapper movie film'],
      ['🎤','microphone sing'],
      ['🎧','headphones music listen'],
      ['🎼','music score notes'],
      ['🎹','piano keyboard music'],
      ['🥁','drum beat music'],
      ['🎷','saxophone jazz music'],
      ['🎺','trumpet music'],
      ['🎸','guitar music rock'],
      ['🎻','violin music'],
      ['🪗','accordion music'],
      ['🎲','dice game random'],
      ['♟️','chess strategy game'],
      ['🎯','bullseye target aim'],
      ['🎳','bowling pins sport'],
      ['🎮','video game controller'],
      ['🎰','slot machine casino'],
      ['🧩','puzzle piece jigsaw'],
      ['🪁','bow arrow archery'],
      ['🎈','balloon party celebrate'],
      ['🎉','party popper celebrate'],
      ['🎊','confetti celebrate'],
      ['🎀','ribbon bow gift'],
      ['🎁','gift present wrap'],
      ['🎃','jack o lantern halloween'],
      ['🎄','christmas tree holiday'],
      ['🎆','fireworks celebrate'],
      ['🎇','sparklers fireworks'],
    ],
  },
  {
    id: 'objects', name: 'Objects', icon: '💡',
    emojis: [
      ['⌚','watch time wrist'],
      ['📱','phone mobile cell'],
      ['💻','laptop computer'],
      ['⌨️','keyboard type'],
      ['🖥️','desktop computer monitor'],
      ['🖨️','printer print'],
      ['🖱️','mouse computer click'],
      ['💽','disc storage data'],
      ['💾','floppy disc save'],
      ['💿','cd disc music'],
      ['📀','dvd disc movie'],
      ['🧮','abacus calculate'],
      ['📷','camera photo picture'],
      ['📸','camera flash photo'],
      ['📹','video camera record'],
      ['🎥','movie camera film'],
      ['📺','television tv screen'],
      ['📻','radio music broadcast'],
      ['📞','phone call telephone'],
      ['☎️','telephone old call'],
      ['📟','pager beeper'],
      ['⏰','alarm clock time wake'],
      ['⏱️','stopwatch time fast'],
      ['⏲️','timer time'],
      ['📡','satellite antenna signal'],
      ['🔋','battery charge power'],
      ['🔌','plug power electric'],
      ['💡','light bulb idea'],
      ['🔦','flashlight torch'],
      ['🕯️','candle light wax'],
      ['💰','money bag rich'],
      ['🪙','coin money'],
      ['💳','credit card payment'],
      ['🧾','receipt purchase'],
      ['💸','flying money cash'],
      ['📈','chart up trend'],
      ['📉','chart down trend'],
      ['📊','bar chart data'],
      ['📋','clipboard list'],
      ['📌','pushpin location'],
      ['📍','pin location'],
      ['✂️','scissors cut'],
      ['🔒','lock locked secure'],
      ['🔓','unlock open'],
      ['🔑','key lock access'],
      ['🗝️','old key'],
      ['🔨','hammer build'],
      ['🪓','axe chop wood'],
      ['⛏️','pick mining'],
      ['🔧','wrench fix repair'],
      ['🔩','nut bolt fix'],
      ['⚙️','gear settings'],
      ['🗜️','clamp compress'],
      ['⚖️','balance scale justice'],
      ['🔗','link chain connect'],
      ['⛓️','chains link'],
      ['🪝','hook catch'],
      ['🧲','magnet attract'],
      ['🪜','ladder climb'],
      ['🧰','toolbox repair'],
      ['🔫','gun pistol weapon'],
      ['🪤','mousetrap trap'],
      ['💎','gem diamond jewel'],
      ['💍','ring engagement marriage'],
      ['👑','crown royal king'],
      ['🏮','lantern red light'],
      ['🪔','lamp oil light'],
      ['📎','paperclip attach'],
      ['📏','ruler straight measure'],
      ['📐','set square measure'],
      ['✏️','pencil write draw'],
      ['✒️','pen write black'],
      ['🖊️','pen write'],
      ['🖋️','fountain pen write'],
      ['📝','memo note write'],
      ['📖','open book read'],
      ['📚','books stack library'],
      ['📁','folder file'],
      ['📂','open folder file'],
      ['🗂️','card index dividers'],
      ['📆','calendar date'],
      ['📅','calendar event'],
      ['📇','card rolodex'],
      ['📬','mailbox letter'],
      ['📭','mailbox empty'],
      ['📦','package box deliver'],
      ['📨','envelope receive'],
      ['📧','email message'],
      ['📩','envelope arrow'],
      ['📪','mailbox closed'],
      ['🗳️','ballot box vote'],
    ],
  },
  {
    id: 'symbols', name: 'Symbols', icon: '💯',
    emojis: [
      ['💯','hundred perfect score'],
      ['🔔','bell notification alert'],
      ['🔕','bell mute silent'],
      ['🔇','mute silent volume'],
      ['🔈','low volume sound'],
      ['🔉','medium volume sound'],
      ['🔊','loud volume sound'],
      ['📢','loudspeaker announce'],
      ['📣','megaphone cheer'],
      ['📯','postal horn music'],
      ['🎵','music note sound'],
      ['🎶','music notes sound'],
      ['✅','check mark done yes'],
      ['❌','cross mark no wrong'],
      ['❓','question mark help'],
      ['❔','white question mark'],
      ['❗','exclamation mark important'],
      ['❕','white exclamation'],
      ['⚠️','warning caution'],
      ['🚫','prohibited no ban'],
      ['🔞','no under eighteen adult'],
      ['📵','no phone'],
      ['🚷','no pedestrians'],
      ['🚯','no littering'],
      ['🚳','no bikes'],
      ['🚱','no water'],
      ['🔴','red circle dot'],
      ['🟠','orange circle'],
      ['🟡','yellow circle'],
      ['🟢','green circle'],
      ['🔵','blue circle'],
      ['🟣','purple circle'],
      ['⚫','black circle'],
      ['⚪','white circle'],
      ['🟤','brown circle'],
      ['🔺','red triangle up'],
      ['🔻','red triangle down'],
      ['🔷','large blue diamond'],
      ['🔶','large orange diamond'],
      ['🔹','small blue diamond'],
      ['🔸','small orange diamond'],
      ['🔳','white square button'],
      ['🔲','black square button'],
      ['▪️','black small square'],
      ['▫️','white small square'],
      ['◾','medium black square'],
      ['◽','medium white square'],
      ['✔️','heavy check mark done'],
      ['💠','diamond blue'],
      ['♾️','infinity loop forever'],
      ['🔁','repeat loop'],
      ['🔂','repeat once'],
      ['▶️','play forward'],
      ['⏩','fast forward'],
      ['⏪','rewind back'],
      ['⏫','fast up'],
      ['⏬','fast down'],
      ['⏸️','pause'],
      ['⏹️','stop'],
      ['⏺️','record'],
      ['🔀','shuffle random'],
      ['🔃','clockwise arrows'],
      ['🔄','counterclockwise arrows'],
      ['🔙','back arrow'],
      ['🔚','end arrow'],
      ['🔛','on arrow'],
      ['🔜','soon arrow'],
      ['🔝','top arrow'],
      ['♻️','recycle green environment'],
      ['💱','currency exchange money'],
      ['💲','dollar sign money'],
      ['©️','copyright'],
      ['®️','registered'],
      ['™️','trademark'],
      ['🆗','ok button'],
      ['🆕','new button'],
      ['🆙','up button'],
      ['🆒','cool button'],
      ['🆓','free button'],
      ['🆘','sos emergency help'],
      ['🏧','atm bank money'],
      ['🚾','wc restroom toilet'],
      ['♿','wheelchair accessible'],
      ['🅿️','parking'],
      ['🚰','potable water'],
      ['🚹','mens restroom'],
      ['🚺','womens restroom'],
      ['🚻','restroom'],
      ['🚼','baby'],
      ['🛗','elevator'],
      ['🛂','passport customs'],
      ['🛃','customs'],
      ['🛄','baggage claim'],
      ['🛅','left luggage'],
      ['🔰','beginner japanese'],
      ['⚜️','fleur de lis'],
    ],
  },
];
